language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"
    - CMAKE_OPTS="-DNetlink=ON -DOpenssl=ON"

matrix:
  include:
    - compiler: clang
    - compiler: gcc

addons:
  apt:
    packages:
    - build-essential
    - libcppunit-dev
    - libnl-3-dev
#    - libnl-cli-3-dev
#    - libnl-genl-3-dev
#    - libnl-nf-3-dev
#    - libnl-route-3-dev
    - libvmime-dev

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir .compile && cd .compile

script:
  - cmake ${CMAKE_OPTS} ..
  - make
#   && make check
