language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"
    - CMAKE_OPTS="-DNetlink=ON -DOpenssl=ON -DTests=ON -DDtnSec=ON -DLowpan=ON -DEnableTls=ON -DCompression=ON"

matrix:
  include:
    - compiler: clang
    - compiler: gcc

addons:
  apt:
    packages:
    - build-essential
    - libcppunit-dev
    - libnl-3-dev
    - libnl-route-3-dev
    - libnl-genl-3-dev

before_install:
#  - pip install --user cpp-coveralls

before_script:
  - set -e
  - mkdir .compile

script:
  - pushd .compile
  - cmake ${CMAKE_OPTS} ..
  - make
  - popd && pushd ibrcommon/tests
  - ../../.compile/ibrcommon/tests/ibrcommon_test
  - popd && pushd ibrdtn/ibrdtn/tests
  - ../../../.compile/ibrdtn/ibrdtn/tests/ibrdtn_test
  - popd && pushd ibrdtn/daemon/tests
  - ../../../.compile/ibrdtn/daemon/tests/dtnd_test
  - ../../../.compile/ibrdtn/daemon/tests/dtnd_unittest
  - popd
